version: "3.8"

services:
  main_service:
    build:
      context: ./main_service/
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    volumes:
      - ./main_service:/app
      - /app/node_modules
  ml_service:
    build:
      context: ./ml_service/
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./ml_service:/app
